using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace THREE
{
    /// <summary>
    /// @author mrdoob / http://mrdoob.com/
    /// @author tengge / https://github.com/tengge1
    /// </summary>
    public sealed class ColorKeywords
    {
        public const int aliceblue = 0xF0F8FF;
        public const int antiquewhite = 0xFAEBD7;
        public const int aqua = 0x00FFFF;
        public const int aquamarine = 0x7FFFD4;
        public const int azure = 0xF0FFFF;
        public const int beige = 0xF5F5DC;
        public const int bisque = 0xFFE4C4;
        public const int black = 0x000000;
        public const int blanchedalmond = 0xFFEBCD;
        public const int blue = 0x0000FF;
        public const int blueviolet = 0x8A2BE2;
        public const int brown = 0xA52A2A;
        public const int burlywood = 0xDEB887;
        public const int cadetblue = 0x5F9EA0;
        public const int chartreuse = 0x7FFF00;
        public const int chocolate = 0xD2691E;
        public const int coral = 0xFF7F50;
        public const int cornflowerblue = 0x6495ED;
        public const int cornsilk = 0xFFF8DC;
        public const int crimson = 0xDC143C;
        public const int cyan = 0x00FFFF;
        public const int darkblue = 0x00008B;
        public const int darkcyan = 0x008B8B;
        public const int darkgoldenrod = 0xB8860B;
        public const int darkgray = 0xA9A9A9;
        public const int darkgreen = 0x006400;
        public const int darkgrey = 0xA9A9A9;
        public const int darkkhaki = 0xBDB76B;
        public const int darkmagenta = 0x8B008B;
        public const int darkolivegreen = 0x556B2F;
        public const int darkorange = 0xFF8C00;
        public const int darkorchid = 0x9932CC;
        public const int darkred = 0x8B0000;
        public const int darksalmon = 0xE9967A;
        public const int darkseagreen = 0x8FBC8F;
        public const int darkslateblue = 0x483D8B;
        public const int darkslategray = 0x2F4F4F;
        public const int darkslategrey = 0x2F4F4F;
        public const int darkturquoise = 0x00CED1;
        public const int darkviolet = 0x9400D3;
        public const int deeppink = 0xFF1493;
        public const int deepskyblue = 0x00BFFF;
        public const int dimgray = 0x696969;
        public const int dimgrey = 0x696969;
        public const int dodgerblue = 0x1E90FF;
        public const int firebrick = 0xB22222;
        public const int floralwhite = 0xFFFAF0;
        public const int forestgreen = 0x228B22;
        public const int fuchsia = 0xFF00FF;
        public const int gainsboro = 0xDCDCDC;
        public const int ghostwhite = 0xF8F8FF;
        public const int gold = 0xFFD700;
        public const int goldenrod = 0xDAA520;
        public const int gray = 0x808080;
        public const int green = 0x008000;
        public const int greenyellow = 0xADFF2F;
        public const int grey = 0x808080;
        public const int honeydew = 0xF0FFF0;
        public const int hotpink = 0xFF69B4;
        public const int indianred = 0xCD5C5C;
        public const int indigo = 0x4B0082;
        public const int ivory = 0xFFFFF0;
        public const int khaki = 0xF0E68C;
        public const int lavender = 0xE6E6FA;
        public const int lavenderblush = 0xFFF0F5;
        public const int lawngreen = 0x7CFC00;
        public const int lemonchiffon = 0xFFFACD;
        public const int lightblue = 0xADD8E6;
        public const int lightcoral = 0xF08080;
        public const int lightcyan = 0xE0FFFF;
        public const int lightgoldenrodyellow = 0xFAFAD2;
        public const int lightgray = 0xD3D3D3;
        public const int lightgreen = 0x90EE90;
        public const int lightgrey = 0xD3D3D3;
        public const int lightpink = 0xFFB6C1;
        public const int lightsalmon = 0xFFA07A;
        public const int lightseagreen = 0x20B2AA;
        public const int lightskyblue = 0x87CEFA;
        public const int lightslategray = 0x778899;
        public const int lightslategrey = 0x778899;
        public const int lightsteelblue = 0xB0C4DE;
        public const int lightyellow = 0xFFFFE0;
        public const int lime = 0x00FF00;
        public const int limegreen = 0x32CD32;
        public const int linen = 0xFAF0E6;
        public const int magenta = 0xFF00FF;
        public const int maroon = 0x800000;
        public const int mediumaquamarine = 0x66CDAA;
        public const int mediumblue = 0x0000CD;
        public const int mediumorchid = 0xBA55D3;
        public const int mediumpurple = 0x9370DB;
        public const int mediumseagreen = 0x3CB371;
        public const int mediumslateblue = 0x7B68EE;
        public const int mediumspringgreen = 0x00FA9A;
        public const int mediumturquoise = 0x48D1CC;
        public const int mediumvioletred = 0xC71585;
        public const int midnightblue = 0x191970;
        public const int mintcream = 0xF5FFFA;
        public const int mistyrose = 0xFFE4E1;
        public const int moccasin = 0xFFE4B5;
        public const int navajowhite = 0xFFDEAD;
        public const int navy = 0x000080;
        public const int oldlace = 0xFDF5E6;
        public const int olive = 0x808000;
        public const int olivedrab = 0x6B8E23;
        public const int orange = 0xFFA500;
        public const int orangered = 0xFF4500;
        public const int orchid = 0xDA70D6;
        public const int palegoldenrod = 0xEEE8AA;
        public const int palegreen = 0x98FB98;
        public const int paleturquoise = 0xAFEEEE;
        public const int palevioletred = 0xDB7093;
        public const int papayawhip = 0xFFEFD5;
        public const int peachpuff = 0xFFDAB9;
        public const int peru = 0xCD853F;
        public const int pink = 0xFFC0CB;
        public const int plum = 0xDDA0DD;
        public const int powderblue = 0xB0E0E6;
        public const int purple = 0x800080;
        public const int rebeccapurple = 0x663399;
        public const int red = 0xFF0000;
        public const int rosybrown = 0xBC8F8F;
        public const int royalblue = 0x4169E1;
        public const int saddlebrown = 0x8B4513;
        public const int salmon = 0xFA8072;
        public const int sandybrown = 0xF4A460;
        public const int seagreen = 0x2E8B57;
        public const int seashell = 0xFFF5EE;
        public const int sienna = 0xA0522D;
        public const int silver = 0xC0C0C0;
        public const int skyblue = 0x87CEEB;
        public const int slateblue = 0x6A5ACD;
        public const int slategray = 0x708090;
        public const int slategrey = 0x708090;
        public const int snow = 0xFFFAFA;
        public const int springgreen = 0x00FF7F;
        public const int steelblue = 0x4682B4;
        public const int tan = 0xD2B48C;
        public const int teal = 0x008080;
        public const int thistle = 0xD8BFD8;
        public const int tomato = 0xFF6347;
        public const int turquoise = 0x40E0D0;
        public const int violet = 0xEE82EE;
        public const int wheat = 0xF5DEB3;
        public const int white = 0xFFFFFF;
        public const int whitesmoke = 0xF5F5F5;
        public const int yellow = 0xFFFF00;
        public const int yellowgreen = 0x9ACD32
    }
}
