// Copyright 2017-2020 The ShadowEditor Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//
// For more information, please visit: https://github.com/tengge1/ShadowEditor
// You can also visit: https://gitee.com/tengge1/ShadowEditor

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: feature_collection.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// FeatureCollection represent a collection of Features.
type FeatureCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bbox     []float64            `protobuf:"fixed64,1,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`
	Points   []*PointFeature      `protobuf:"bytes,2,rep,name=points,proto3" json:"points,omitempty"`
	Lines    []*LineStringFeature `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	Polygons []*PolygonFeature    `protobuf:"bytes,4,rep,name=polygons,proto3" json:"polygons,omitempty"`
}

func (x *FeatureCollection) Reset() {
	*x = FeatureCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_feature_collection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureCollection) ProtoMessage() {}

func (x *FeatureCollection) ProtoReflect() protoreflect.Message {
	mi := &file_feature_collection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureCollection.ProtoReflect.Descriptor instead.
func (*FeatureCollection) Descriptor() ([]byte, []int) {
	return file_feature_collection_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureCollection) GetBbox() []float64 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *FeatureCollection) GetPoints() []*PointFeature {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *FeatureCollection) GetLines() []*LineStringFeature {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *FeatureCollection) GetPolygons() []*PolygonFeature {
	if x != nil {
		return x.Polygons
	}
	return nil
}

var File_feature_collection_proto protoreflect.FileDescriptor

var file_feature_collection_proto_rawDesc = []byte{
	0x0a, 0x18, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x13,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xae, 0x01, 0x0a, 0x11, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x62,
	0x6f, 0x78, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x12, 0x28,
	0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x2b, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x6e,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x05,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x08, 0x70, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_feature_collection_proto_rawDescOnce sync.Once
	file_feature_collection_proto_rawDescData = file_feature_collection_proto_rawDesc
)

func file_feature_collection_proto_rawDescGZIP() []byte {
	file_feature_collection_proto_rawDescOnce.Do(func() {
		file_feature_collection_proto_rawDescData = protoimpl.X.CompressGZIP(file_feature_collection_proto_rawDescData)
	})
	return file_feature_collection_proto_rawDescData
}

var file_feature_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_feature_collection_proto_goTypes = []interface{}{
	(*FeatureCollection)(nil), // 0: pb.FeatureCollection
	(*PointFeature)(nil),      // 1: pb.PointFeature
	(*LineStringFeature)(nil), // 2: pb.LineStringFeature
	(*PolygonFeature)(nil),    // 3: pb.PolygonFeature
}
var file_feature_collection_proto_depIdxs = []int32{
	1, // 0: pb.FeatureCollection.points:type_name -> pb.PointFeature
	2, // 1: pb.FeatureCollection.lines:type_name -> pb.LineStringFeature
	3, // 2: pb.FeatureCollection.polygons:type_name -> pb.PolygonFeature
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_feature_collection_proto_init() }
func file_feature_collection_proto_init() {
	if File_feature_collection_proto != nil {
		return
	}
	file_point_feature_proto_init()
	file_linestring_feature_proto_init()
	file_polygon_feature_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_feature_collection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_feature_collection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feature_collection_proto_goTypes,
		DependencyIndexes: file_feature_collection_proto_depIdxs,
		MessageInfos:      file_feature_collection_proto_msgTypes,
	}.Build()
	File_feature_collection_proto = out.File
	file_feature_collection_proto_rawDesc = nil
	file_feature_collection_proto_goTypes = nil
	file_feature_collection_proto_depIdxs = nil
}
