// Copyright 2017-2020 The ShadowEditor Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//
// For more information, please visit: https://github.com/tengge1/ShadowEditor
// You can also visit: https://gitee.com/tengge1/ShadowEditor

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: linestring_feature.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// LineStringFeature represent a line element.
type LineStringFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bbox       []float64                `protobuf:"fixed64,2,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`
	Geometry   *LineStringGeometry      `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Properties map[string]*VariantValue `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LineStringFeature) Reset() {
	*x = LineStringFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linestring_feature_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineStringFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineStringFeature) ProtoMessage() {}

func (x *LineStringFeature) ProtoReflect() protoreflect.Message {
	mi := &file_linestring_feature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineStringFeature.ProtoReflect.Descriptor instead.
func (*LineStringFeature) Descriptor() ([]byte, []int) {
	return file_linestring_feature_proto_rawDescGZIP(), []int{0}
}

func (x *LineStringFeature) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LineStringFeature) GetBbox() []float64 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *LineStringFeature) GetGeometry() *LineStringGeometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *LineStringFeature) GetProperties() map[string]*VariantValue {
	if x != nil {
		return x.Properties
	}
	return nil
}

// LineStringGeometry is the geometry on a LineStringFeature.
type LineStringGeometry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates []*Coordinate `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *LineStringGeometry) Reset() {
	*x = LineStringGeometry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linestring_feature_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LineStringGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineStringGeometry) ProtoMessage() {}

func (x *LineStringGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_linestring_feature_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineStringGeometry.ProtoReflect.Descriptor instead.
func (*LineStringGeometry) Descriptor() ([]byte, []int) {
	return file_linestring_feature_proto_rawDescGZIP(), []int{1}
}

func (x *LineStringGeometry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LineStringGeometry) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

var File_linestring_feature_proto protoreflect.FileDescriptor

var file_linestring_feature_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x10,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x13, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x02, 0x0a, 0x11, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x62, 0x6f, 0x78, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x12,
	0x32, 0x0a, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x52, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x12, 0x45, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x6e,
	0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x4f, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5a, 0x0a, 0x12, 0x4c,
	0x69, 0x6e, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linestring_feature_proto_rawDescOnce sync.Once
	file_linestring_feature_proto_rawDescData = file_linestring_feature_proto_rawDesc
)

func file_linestring_feature_proto_rawDescGZIP() []byte {
	file_linestring_feature_proto_rawDescOnce.Do(func() {
		file_linestring_feature_proto_rawDescData = protoimpl.X.CompressGZIP(file_linestring_feature_proto_rawDescData)
	})
	return file_linestring_feature_proto_rawDescData
}

var file_linestring_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_linestring_feature_proto_goTypes = []interface{}{
	(*LineStringFeature)(nil),  // 0: pb.LineStringFeature
	(*LineStringGeometry)(nil), // 1: pb.LineStringGeometry
	nil,                        // 2: pb.LineStringFeature.PropertiesEntry
	(*Coordinate)(nil),         // 3: pb.Coordinate
	(*VariantValue)(nil),       // 4: pb.VariantValue
}
var file_linestring_feature_proto_depIdxs = []int32{
	1, // 0: pb.LineStringFeature.geometry:type_name -> pb.LineStringGeometry
	2, // 1: pb.LineStringFeature.properties:type_name -> pb.LineStringFeature.PropertiesEntry
	3, // 2: pb.LineStringGeometry.coordinates:type_name -> pb.Coordinate
	4, // 3: pb.LineStringFeature.PropertiesEntry.value:type_name -> pb.VariantValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_linestring_feature_proto_init() }
func file_linestring_feature_proto_init() {
	if File_linestring_feature_proto != nil {
		return
	}
	file_coordinate_proto_init()
	file_variant_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_linestring_feature_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineStringFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linestring_feature_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LineStringGeometry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linestring_feature_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_linestring_feature_proto_goTypes,
		DependencyIndexes: file_linestring_feature_proto_depIdxs,
		MessageInfos:      file_linestring_feature_proto_msgTypes,
	}.Build()
	File_linestring_feature_proto = out.File
	file_linestring_feature_proto_rawDesc = nil
	file_linestring_feature_proto_goTypes = nil
	file_linestring_feature_proto_depIdxs = nil
}
