// Copyright 2017-2020 The ShadowEditor Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//
// For more information, please visit: https://github.com/tengge1/ShadowEditor
// You can also visit: https://gitee.com/tengge1/ShadowEditor

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: polygon_feature.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// PolygonFeature represent a polygon element.
type PolygonFeature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bbox       []float64                `protobuf:"fixed64,2,rep,packed,name=bbox,proto3" json:"bbox,omitempty"`
	Geometry   *PolygonGeometry         `protobuf:"bytes,3,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Properties map[string]*VariantValue `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PolygonFeature) Reset() {
	*x = PolygonFeature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polygon_feature_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolygonFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolygonFeature) ProtoMessage() {}

func (x *PolygonFeature) ProtoReflect() protoreflect.Message {
	mi := &file_polygon_feature_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolygonFeature.ProtoReflect.Descriptor instead.
func (*PolygonFeature) Descriptor() ([]byte, []int) {
	return file_polygon_feature_proto_rawDescGZIP(), []int{0}
}

func (x *PolygonFeature) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolygonFeature) GetBbox() []float64 {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *PolygonFeature) GetGeometry() *PolygonGeometry {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *PolygonFeature) GetProperties() map[string]*VariantValue {
	if x != nil {
		return x.Properties
	}
	return nil
}

// PolygonGeometry is the geometry on a PolygonFeature.
type PolygonGeometry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates []*Coordinates `protobuf:"bytes,2,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *PolygonGeometry) Reset() {
	*x = PolygonGeometry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_polygon_feature_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolygonGeometry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolygonGeometry) ProtoMessage() {}

func (x *PolygonGeometry) ProtoReflect() protoreflect.Message {
	mi := &file_polygon_feature_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolygonGeometry.ProtoReflect.Descriptor instead.
func (*PolygonGeometry) Descriptor() ([]byte, []int) {
	return file_polygon_feature_proto_rawDescGZIP(), []int{1}
}

func (x *PolygonGeometry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PolygonGeometry) GetCoordinates() []*Coordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

var File_polygon_feature_proto protoreflect.FileDescriptor

var file_polygon_feature_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x11, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xfa, 0x01, 0x0a, 0x0e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x62, 0x62, 0x6f, 0x78, 0x12, 0x2f, 0x0a, 0x08, 0x67, 0x65,
	0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x47, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x52, 0x08, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x12, 0x42, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x46, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x1a,
	0x4f, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x58, 0x0a, 0x0f, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x47, 0x65, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x0b, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_polygon_feature_proto_rawDescOnce sync.Once
	file_polygon_feature_proto_rawDescData = file_polygon_feature_proto_rawDesc
)

func file_polygon_feature_proto_rawDescGZIP() []byte {
	file_polygon_feature_proto_rawDescOnce.Do(func() {
		file_polygon_feature_proto_rawDescData = protoimpl.X.CompressGZIP(file_polygon_feature_proto_rawDescData)
	})
	return file_polygon_feature_proto_rawDescData
}

var file_polygon_feature_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_polygon_feature_proto_goTypes = []interface{}{
	(*PolygonFeature)(nil),  // 0: pb.PolygonFeature
	(*PolygonGeometry)(nil), // 1: pb.PolygonGeometry
	nil,                     // 2: pb.PolygonFeature.PropertiesEntry
	(*Coordinates)(nil),     // 3: pb.Coordinates
	(*VariantValue)(nil),    // 4: pb.VariantValue
}
var file_polygon_feature_proto_depIdxs = []int32{
	1, // 0: pb.PolygonFeature.geometry:type_name -> pb.PolygonGeometry
	2, // 1: pb.PolygonFeature.properties:type_name -> pb.PolygonFeature.PropertiesEntry
	3, // 2: pb.PolygonGeometry.coordinates:type_name -> pb.Coordinates
	4, // 3: pb.PolygonFeature.PropertiesEntry.value:type_name -> pb.VariantValue
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_polygon_feature_proto_init() }
func file_polygon_feature_proto_init() {
	if File_polygon_feature_proto != nil {
		return
	}
	file_coordinates_proto_init()
	file_variant_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_polygon_feature_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolygonFeature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_polygon_feature_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolygonGeometry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_polygon_feature_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_polygon_feature_proto_goTypes,
		DependencyIndexes: file_polygon_feature_proto_depIdxs,
		MessageInfos:      file_polygon_feature_proto_msgTypes,
	}.Build()
	File_polygon_feature_proto = out.File
	file_polygon_feature_proto_rawDesc = nil
	file_polygon_feature_proto_goTypes = nil
	file_polygon_feature_proto_depIdxs = nil
}
