// Copyright 2017-2020 The ShadowEditor Authors. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.
//
// For more information, please visit: https://github.com/tengge1/ShadowEditor
// You can also visit: https://gitee.com/tengge1/ShadowEditor

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: variant_value.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// VariantValue is a value that has different types.
type VariantValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*VariantValue_Double
	//	*VariantValue_Float
	//	*VariantValue_Int32
	//	*VariantValue_Int64
	//	*VariantValue_Uint32
	//	*VariantValue_Uint64
	//	*VariantValue_Sint32
	//	*VariantValue_Sint64
	//	*VariantValue_Fixed32
	//	*VariantValue_Fixed64
	//	*VariantValue_Sfixed32
	//	*VariantValue_Sfixed64
	//	*VariantValue_Bool
	//	*VariantValue_String_
	//	*VariantValue_Bytes
	Value isVariantValue_Value `protobuf_oneof:"Value"`
}

func (x *VariantValue) Reset() {
	*x = VariantValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_variant_value_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariantValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantValue) ProtoMessage() {}

func (x *VariantValue) ProtoReflect() protoreflect.Message {
	mi := &file_variant_value_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantValue.ProtoReflect.Descriptor instead.
func (*VariantValue) Descriptor() ([]byte, []int) {
	return file_variant_value_proto_rawDescGZIP(), []int{0}
}

func (m *VariantValue) GetValue() isVariantValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *VariantValue) GetDouble() float64 {
	if x, ok := x.GetValue().(*VariantValue_Double); ok {
		return x.Double
	}
	return 0
}

func (x *VariantValue) GetFloat() float32 {
	if x, ok := x.GetValue().(*VariantValue_Float); ok {
		return x.Float
	}
	return 0
}

func (x *VariantValue) GetInt32() int32 {
	if x, ok := x.GetValue().(*VariantValue_Int32); ok {
		return x.Int32
	}
	return 0
}

func (x *VariantValue) GetInt64() int64 {
	if x, ok := x.GetValue().(*VariantValue_Int64); ok {
		return x.Int64
	}
	return 0
}

func (x *VariantValue) GetUint32() uint32 {
	if x, ok := x.GetValue().(*VariantValue_Uint32); ok {
		return x.Uint32
	}
	return 0
}

func (x *VariantValue) GetUint64() uint64 {
	if x, ok := x.GetValue().(*VariantValue_Uint64); ok {
		return x.Uint64
	}
	return 0
}

func (x *VariantValue) GetSint32() int32 {
	if x, ok := x.GetValue().(*VariantValue_Sint32); ok {
		return x.Sint32
	}
	return 0
}

func (x *VariantValue) GetSint64() int64 {
	if x, ok := x.GetValue().(*VariantValue_Sint64); ok {
		return x.Sint64
	}
	return 0
}

func (x *VariantValue) GetFixed32() uint32 {
	if x, ok := x.GetValue().(*VariantValue_Fixed32); ok {
		return x.Fixed32
	}
	return 0
}

func (x *VariantValue) GetFixed64() uint64 {
	if x, ok := x.GetValue().(*VariantValue_Fixed64); ok {
		return x.Fixed64
	}
	return 0
}

func (x *VariantValue) GetSfixed32() int32 {
	if x, ok := x.GetValue().(*VariantValue_Sfixed32); ok {
		return x.Sfixed32
	}
	return 0
}

func (x *VariantValue) GetSfixed64() int64 {
	if x, ok := x.GetValue().(*VariantValue_Sfixed64); ok {
		return x.Sfixed64
	}
	return 0
}

func (x *VariantValue) GetBool() bool {
	if x, ok := x.GetValue().(*VariantValue_Bool); ok {
		return x.Bool
	}
	return false
}

func (x *VariantValue) GetString_() string {
	if x, ok := x.GetValue().(*VariantValue_String_); ok {
		return x.String_
	}
	return ""
}

func (x *VariantValue) GetBytes() []byte {
	if x, ok := x.GetValue().(*VariantValue_Bytes); ok {
		return x.Bytes
	}
	return nil
}

type isVariantValue_Value interface {
	isVariantValue_Value()
}

type VariantValue_Double struct {
	Double float64 `protobuf:"fixed64,1,opt,name=Double,proto3,oneof"`
}

type VariantValue_Float struct {
	Float float32 `protobuf:"fixed32,2,opt,name=Float,proto3,oneof"`
}

type VariantValue_Int32 struct {
	Int32 int32 `protobuf:"varint,3,opt,name=Int32,proto3,oneof"`
}

type VariantValue_Int64 struct {
	Int64 int64 `protobuf:"varint,4,opt,name=Int64,proto3,oneof"`
}

type VariantValue_Uint32 struct {
	Uint32 uint32 `protobuf:"varint,5,opt,name=Uint32,proto3,oneof"`
}

type VariantValue_Uint64 struct {
	Uint64 uint64 `protobuf:"varint,6,opt,name=Uint64,proto3,oneof"`
}

type VariantValue_Sint32 struct {
	Sint32 int32 `protobuf:"zigzag32,7,opt,name=Sint32,proto3,oneof"`
}

type VariantValue_Sint64 struct {
	Sint64 int64 `protobuf:"zigzag64,8,opt,name=Sint64,proto3,oneof"`
}

type VariantValue_Fixed32 struct {
	Fixed32 uint32 `protobuf:"fixed32,9,opt,name=Fixed32,proto3,oneof"`
}

type VariantValue_Fixed64 struct {
	Fixed64 uint64 `protobuf:"fixed64,10,opt,name=Fixed64,proto3,oneof"`
}

type VariantValue_Sfixed32 struct {
	Sfixed32 int32 `protobuf:"fixed32,11,opt,name=Sfixed32,proto3,oneof"`
}

type VariantValue_Sfixed64 struct {
	Sfixed64 int64 `protobuf:"fixed64,12,opt,name=Sfixed64,proto3,oneof"`
}

type VariantValue_Bool struct {
	Bool bool `protobuf:"varint,13,opt,name=Bool,proto3,oneof"`
}

type VariantValue_String_ struct {
	String_ string `protobuf:"bytes,14,opt,name=String,proto3,oneof"`
}

type VariantValue_Bytes struct {
	Bytes []byte `protobuf:"bytes,15,opt,name=Bytes,proto3,oneof"`
}

func (*VariantValue_Double) isVariantValue_Value() {}

func (*VariantValue_Float) isVariantValue_Value() {}

func (*VariantValue_Int32) isVariantValue_Value() {}

func (*VariantValue_Int64) isVariantValue_Value() {}

func (*VariantValue_Uint32) isVariantValue_Value() {}

func (*VariantValue_Uint64) isVariantValue_Value() {}

func (*VariantValue_Sint32) isVariantValue_Value() {}

func (*VariantValue_Sint64) isVariantValue_Value() {}

func (*VariantValue_Fixed32) isVariantValue_Value() {}

func (*VariantValue_Fixed64) isVariantValue_Value() {}

func (*VariantValue_Sfixed32) isVariantValue_Value() {}

func (*VariantValue_Sfixed64) isVariantValue_Value() {}

func (*VariantValue_Bool) isVariantValue_Value() {}

func (*VariantValue_String_) isVariantValue_Value() {}

func (*VariantValue_Bytes) isVariantValue_Value() {}

var File_variant_value_proto protoreflect.FileDescriptor

var file_variant_value_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x9d, 0x03, 0x0a, 0x0c, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x05, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x12, 0x16, 0x0a, 0x05,
	0x49, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x49,
	0x6e, 0x74, 0x33, 0x32, 0x12, 0x16, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x05, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x18, 0x0a, 0x06,
	0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x06,
	0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x06, 0x55, 0x69, 0x6e, 0x74, 0x36, 0x34,
	0x12, 0x18, 0x0a, 0x06, 0x53, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x11,
	0x48, 0x00, 0x52, 0x06, 0x53, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x18, 0x0a, 0x06, 0x53, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x18, 0x08, 0x20, 0x01, 0x28, 0x12, 0x48, 0x00, 0x52, 0x06, 0x53, 0x69,
	0x6e, 0x74, 0x36, 0x34, 0x12, 0x1a, 0x0a, 0x07, 0x46, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x07, 0x48, 0x00, 0x52, 0x07, 0x46, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32,
	0x12, 0x1a, 0x0a, 0x07, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x06, 0x48, 0x00, 0x52, 0x07, 0x46, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x1c, 0x0a, 0x08,
	0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0f, 0x48, 0x00,
	0x52, 0x08, 0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x33, 0x32, 0x12, 0x1c, 0x0a, 0x08, 0x53, 0x66,
	0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x10, 0x48, 0x00, 0x52, 0x08,
	0x53, 0x66, 0x69, 0x78, 0x65, 0x64, 0x36, 0x34, 0x12, 0x14, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6c,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x18,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x42, 0x07, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_variant_value_proto_rawDescOnce sync.Once
	file_variant_value_proto_rawDescData = file_variant_value_proto_rawDesc
)

func file_variant_value_proto_rawDescGZIP() []byte {
	file_variant_value_proto_rawDescOnce.Do(func() {
		file_variant_value_proto_rawDescData = protoimpl.X.CompressGZIP(file_variant_value_proto_rawDescData)
	})
	return file_variant_value_proto_rawDescData
}

var file_variant_value_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_variant_value_proto_goTypes = []interface{}{
	(*VariantValue)(nil), // 0: pb.VariantValue
}
var file_variant_value_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_variant_value_proto_init() }
func file_variant_value_proto_init() {
	if File_variant_value_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_variant_value_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariantValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_variant_value_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*VariantValue_Double)(nil),
		(*VariantValue_Float)(nil),
		(*VariantValue_Int32)(nil),
		(*VariantValue_Int64)(nil),
		(*VariantValue_Uint32)(nil),
		(*VariantValue_Uint64)(nil),
		(*VariantValue_Sint32)(nil),
		(*VariantValue_Sint64)(nil),
		(*VariantValue_Fixed32)(nil),
		(*VariantValue_Fixed64)(nil),
		(*VariantValue_Sfixed32)(nil),
		(*VariantValue_Sfixed64)(nil),
		(*VariantValue_Bool)(nil),
		(*VariantValue_String_)(nil),
		(*VariantValue_Bytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_variant_value_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_variant_value_proto_goTypes,
		DependencyIndexes: file_variant_value_proto_depIdxs,
		MessageInfos:      file_variant_value_proto_msgTypes,
	}.Build()
	File_variant_value_proto = out.File
	file_variant_value_proto_rawDesc = nil
	file_variant_value_proto_goTypes = nil
	file_variant_value_proto_depIdxs = nil
}
